# ALIASES
alias vz="vim ~/.zshrc"
alias zsrc="source ~/.zshrc"
alias va="vim ~/.dotfiles/alias.zsh"
alias vf="vim ~/.dotfiles/functions.zsh"

# GIT
alias gc="git clone"
alias gs="git status"
alias gd="git diff"
alias gb="git branch"
alias gpl="git pull origin "$(git_current_branch)"
alias gplm="git pull origin main"
alias ga="git add ."
alias gcm="git commit -m"
alias gca="git commit --amend"
alias gch="git cherry-pick"
alias gps="git push"
alias gpsm="git push --set-upstream origin main"
alias gck="git checkout"
alias gcb="git checkout -b"
alias gckm="git checkout main"
alias gsh="git stash"
alias gsp="git stash pop"
alias gsl="git stash list"
